name: Test Docker Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.dockerignore'
      - 'package*.json'
      - 'apps/**'
      - 'packages/**'
      - 'tools/**'
      - '.github/workflows/docker-build-test.yml'

permissions:
  contents: read
  pull-requests: write  # Required for commenting on PRs
  security-events: write  # For uploading SARIF files

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type checking
        run: npm run check

      - name: Build application
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          ignore: DL3008,DL3009,DL3018  # DL3018: Pin versions in Alpine (not always practical)

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            astromich:test-${{ github.event.pull_request.number }}
            astromich:test-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true  # Load image for local testing

      - name: Test Docker image structure
        run: |
          docker buildx build --load -t astromich:test-${{ github.event.pull_request.number }} .
          
          echo "## Docker Image Test Results 🧪" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Test if the image was built successfully
          if docker image inspect astromich:test-${{ github.event.pull_request.number }} > /dev/null 2>&1; then
            echo "✅ **Image built successfully**" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Image build failed**" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          
          # Check image size
          IMAGE_SIZE=$(docker image inspect astromich:test-${{ github.event.pull_request.number }} --format='{{.Size}}' | numfmt --to=iec-i --suffix=B)
          echo "📦 **Image size:** $IMAGE_SIZE" >> $GITHUB_STEP_SUMMARY
          
          # Test if required directories exist
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Directory Structure Check" >> $GITHUB_STEP_SUMMARY
          docker run --rm astromich:test-${{ github.event.pull_request.number }} ls -la /app/dist > /dev/null 2>&1 && echo "✅ /app/dist exists" >> $GITHUB_STEP_SUMMARY || echo "❌ /app/dist missing" >> $GITHUB_STEP_SUMMARY
          docker run --rm astromich:test-${{ github.event.pull_request.number }} ls -la /app/config > /dev/null 2>&1 && echo "✅ /app/config exists" >> $GITHUB_STEP_SUMMARY || echo "❌ /app/config missing" >> $GITHUB_STEP_SUMMARY
          docker run --rm astromich:test-${{ github.event.pull_request.number }} ls -la /app/logs > /dev/null 2>&1 && echo "✅ /app/logs exists" >> $GITHUB_STEP_SUMMARY || echo "❌ /app/logs missing" >> $GITHUB_STEP_SUMMARY
          docker run --rm astromich:test-${{ github.event.pull_request.number }} ls -la /app/sidecars > /dev/null 2>&1 && echo "✅ /app/sidecars exists" >> $GITHUB_STEP_SUMMARY || echo "❌ /app/sidecars missing" >> $GITHUB_STEP_SUMMARY
          
          # Check if startup script is executable
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Startup Script Check" >> $GITHUB_STEP_SUMMARY
          docker run --rm --entrypoint="" astromich:test-${{ github.event.pull_request.number }} test -x /app/startup.sh && echo "✅ startup.sh is executable" >> $GITHUB_STEP_SUMMARY || echo "❌ startup.sh is not executable" >> $GITHUB_STEP_SUMMARY

      - name: Run container smoke test
        run: |
          # Start container with minimal config
          docker run -d \
            --name astromich-test \
            -p 5000:5000 \
            -e NODE_ENV=production \
            -e DATABASE_URL=postgresql://test:test@localhost:5432/test \
            astromich:test-${{ github.event.pull_request.number }}
          
          # Give it time to start (or fail)
          sleep 10
          
          # Check if container is still running
          if docker ps | grep -q astromich-test; then
            echo "✅ Container started successfully" >> $GITHUB_STEP_SUMMARY
            docker logs astromich-test
          else
            echo "❌ Container failed to start" >> $GITHUB_STEP_SUMMARY
            docker logs astromich-test
            exit 1
          fi
          
          # Cleanup
          docker stop astromich-test || true
          docker rm astromich-test || true

      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: astromich:test-${{ github.event.pull_request.number }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'  # Don't fail PR builds on vulnerabilities

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy-pr'

      - name: Generate vulnerability report
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: astromich:test-${{ github.event.pull_request.number }}
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'
          output: 'trivy-report.txt'

      - name: Comment PR with results
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs');
            let trivyReport = '';
            
            try {
              trivyReport = fs.readFileSync('trivy-report.txt', 'utf8');
              if (trivyReport.trim()) {
                trivyReport = '\n\n<details>\n<summary>Vulnerability Scan Results</summary>\n\n```\n' + trivyReport + '\n```\n</details>';
              } else {
                trivyReport = '\n\n✅ **No vulnerabilities found!**';
              }
            } catch (e) {
              trivyReport = '';
            }
            
            const output = `#### Docker Build Test 🐳
            
            ✅ **All checks passed!**
            
            - TypeScript compilation successful
            - Application build successful
            - Docker image builds successfully
            - Container starts without errors
            ${trivyReport}
            
            View the full test results in the [Actions summary](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })